<?php

define('PRETTY_CHECKABLE_FIELD_DIR', basename(dirname(__FILE__)));
define('PRETTY_CHECKABLE_FIELD_JAVASCRIPT', PRETTY_CHECKABLE_FIELD_DIR.'/javascript/');
define('PRETTY_CHECKABLE_FIELD_THIRDPARTY', PRETTY_CHECKABLE_FIELD_JAVASCRIPT.'thirdparty');